#!/usr/bin/env bash
# Lift the public-header subset of each vendor submodule into ge/headers/.
#
# Run from the ge repo root. Requires all submodules to be initialized
# (git submodule update --init --recursive). The lifted tree is committed
# as plain git files (not LFS) — it's ~20MB total across all vendors.
#
# Consumer apps' iOS xcodeproj (generated by ge/tools/ios-build/build_project.rb)
# reads from ge/headers/<vendor>/include/ instead of ge/vendor/github.com/<org>/<vendor>/include/,
# so consumer CI can check out ge with submodules: true (NOT recursive) and
# skip ge's own ~150MB of nested submodule clones.
#
# Re-running is idempotent — overwrites the destinations.
#
# Refresh workflow: bump submodule SHAs, then re-run prebuild-vendor-ios-arm64.sh
# + this script, then commit. See docs/vendor-prebuilds.md.
#
# Copyright 2026 Marcelo Cantos
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

GE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$GE_ROOT"

OUT="headers"
rm -rf "$OUT"
mkdir -p "$OUT"

VENDOR="vendor/github.com"
BOX2D_DIR="$VENDOR/erincatto/box2d"
LUNASVG_DIR="$VENDOR/sammycage/lunasvg"
PLUTOVG_DIR="$LUNASVG_DIR/plutovg"
LITEPARSER_DIR="$VENDOR/sqliteai/liteparser/src"
SDL_DIR="$VENDOR/libsdl-org/SDL"
SDL_TTF_DIR="$VENDOR/libsdl-org/SDL_ttf"
FREETYPE_INC="$SDL_TTF_DIR/external/freetype/include"
SPDLOG_DIR="$VENDOR/gabime/spdlog"
ASIO_DIR="$VENDOR/chriskohlhoff/asio"

# Sanity check — submodules must be initialized (liteparser is plain files).
for d in "$BOX2D_DIR" "$LUNASVG_DIR" "$SDL_DIR" "$FREETYPE_INC" "$SPDLOG_DIR" "$ASIO_DIR"; do
  if [[ ! -d "$d/include" && "$d" != "$BOX2D_DIR" && "$d" != "$FREETYPE_INC" ]]; then
    echo "error: $d/include missing. Run: git submodule update --init --recursive" >&2
    exit 1
  fi
  # Special-case nested FreeType submodule inside SDL_ttf.
  if [[ "$d" == "$FREETYPE_INC" && ! -f "$d/ft2build.h" ]]; then
    echo "error: $d/ft2build.h missing. Run: git submodule update --init --recursive" >&2
    exit 1
  fi
done

# ─── box2d ─────────────────────────────────────────────────────────────
mkdir -p "$OUT/box2d/include"
rsync -a "$BOX2D_DIR/include/" "$OUT/box2d/include/"

# ─── lunasvg ───────────────────────────────────────────────────────────
mkdir -p "$OUT/lunasvg/include"
rsync -a "$LUNASVG_DIR/include/" "$OUT/lunasvg/include/"

# ─── plutovg ───────────────────────────────────────────────────────────
mkdir -p "$OUT/plutovg/include"
rsync -a "$PLUTOVG_DIR/include/" "$OUT/plutovg/include/"

# ─── liteparser ────────────────────────────────────────────────────────
# Liteparser ships headers next to sources (no include/ subdir). Lift the
# public .h files into headers/liteparser/include/.
mkdir -p "$OUT/liteparser/include"
cp "$LITEPARSER_DIR"/arena.h          "$OUT/liteparser/include/"
cp "$LITEPARSER_DIR"/liteparser.h     "$OUT/liteparser/include/"
cp "$LITEPARSER_DIR"/liteparser_internal.h "$OUT/liteparser/include/"
cp "$LITEPARSER_DIR"/parse.h          "$OUT/liteparser/include/"

# ─── SDL3 core + freetype ──────────────────────────────────────────────
# SDL3 core, freetype, plutosvg, plutovg, harfbuzz prebuilt static libs
# already live under vendor/sdl3/lib/{ios-arm64,macos-arm64}/, and the
# SDL3_image / SDL3_ttf header dirs were already committed under
# vendor/sdl3/include/. The core SDL3 headers + freetype headers were
# being pulled from the libsdl-org/SDL and SDL_ttf/external/freetype
# submodules, which made consumer iOS CI need recursive submodule init.
# Lift them alongside the prebuilt libs so consumers see the whole
# "SDL3 stack" under one tree.
mkdir -p "$OUT/sdl3/include/SDL3"
rsync -a "$SDL_DIR/include/SDL3/" "$OUT/sdl3/include/SDL3/"
# build_directory.h is generated by SDL's build; if not present in the
# submodule, skip (a real SDL3 release tarball would have it). Today we
# accept whatever the submodule ships.

# FreeType: the freetype/include tree has ft2build.h at the root and a
# freetype/ subdir of headers. Lift both into headers/sdl3/include/.
rsync -a "$FREETYPE_INC/" "$OUT/sdl3/include/"

# ─── spdlog (header-only) ──────────────────────────────────────────────
mkdir -p "$OUT/spdlog/include"
rsync -a "$SPDLOG_DIR/include/" "$OUT/spdlog/include/"

# ─── asio (header-only) ────────────────────────────────────────────────
mkdir -p "$OUT/asio/include"
rsync -a "$ASIO_DIR/include/" "$OUT/asio/include/"

# ─── summary ──────────────────────────────────────────────────────────
echo "── lifted headers ──"
du -sh "$OUT"/*/include | awk '{printf "  %-40s %s\n", $2, $1}'
echo ""
echo "Total: $(du -sh "$OUT" | cut -f1)"
