#!/usr/bin/env bash
# Lift the public-header subset of each vendor submodule into ge/headers/.
#
# Run from the ge repo root. Requires all submodules to be initialized
# (git submodule update --init --recursive). The lifted tree is committed
# as plain git files (not LFS) — it's ~20MB total across all vendors.
#
# Consumer apps' iOS xcodeproj (generated by ge/tools/ios-build/build_project.rb)
# reads from ge/headers/<vendor>/include/ instead of ge/vendor/github.com/<org>/<vendor>/include/,
# so consumer CI can check out ge with submodules: true (NOT recursive) and
# skip ge's own ~150MB of nested submodule clones.
#
# Re-running is idempotent — overwrites the destinations.
#
# Refresh workflow: bump submodule SHAs, then re-run prebuild-vendor-ios-arm64.sh
# + this script, then commit. See docs/vendor-prebuilds.md.
#
# Copyright 2026 Marcelo Cantos
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

GE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$GE_ROOT"

OUT="headers"
rm -rf "$OUT"
mkdir -p "$OUT"

VENDOR="vendor/github.com"
BX_DIR="$VENDOR/bkaradzic/bx"
BIMG_DIR="$VENDOR/bkaradzic/bimg"
BGFX_DIR="$VENDOR/bkaradzic/bgfx"
BOX2D_DIR="$VENDOR/erincatto/box2d"
LUNASVG_DIR="$VENDOR/sammycage/lunasvg"
PLUTOVG_DIR="$LUNASVG_DIR/plutovg"
LITEPARSER_DIR="$VENDOR/sqliteai/liteparser/src"

# Sanity check — submodules must be initialized (liteparser is plain files).
for d in "$BX_DIR" "$BIMG_DIR" "$BGFX_DIR" "$BOX2D_DIR" "$LUNASVG_DIR"; do
  if [[ ! -d "$d/include" && "$d" != "$BOX2D_DIR" ]]; then
    echo "error: $d/include missing. Run: git submodule update --init --recursive" >&2
    exit 1
  fi
done

# ─── bx ────────────────────────────────────────────────────────────────
mkdir -p "$OUT/bx/include"
rsync -a "$BX_DIR/include/" "$OUT/bx/include/"

# ─── bimg ──────────────────────────────────────────────────────────────
mkdir -p "$OUT/bimg/include"
rsync -a "$BIMG_DIR/include/" "$OUT/bimg/include/"

# ─── bgfx ──────────────────────────────────────────────────────────────
mkdir -p "$OUT/bgfx/include"
rsync -a "$BGFX_DIR/include/" "$OUT/bgfx/include/"

# ─── box2d ─────────────────────────────────────────────────────────────
mkdir -p "$OUT/box2d/include"
rsync -a "$BOX2D_DIR/include/" "$OUT/box2d/include/"

# ─── lunasvg ───────────────────────────────────────────────────────────
mkdir -p "$OUT/lunasvg/include"
rsync -a "$LUNASVG_DIR/include/" "$OUT/lunasvg/include/"

# ─── plutovg ───────────────────────────────────────────────────────────
mkdir -p "$OUT/plutovg/include"
rsync -a "$PLUTOVG_DIR/include/" "$OUT/plutovg/include/"

# ─── liteparser ────────────────────────────────────────────────────────
# Liteparser ships headers next to sources (no include/ subdir). Lift the
# public .h files into headers/liteparser/include/.
mkdir -p "$OUT/liteparser/include"
cp "$LITEPARSER_DIR"/arena.h          "$OUT/liteparser/include/"
cp "$LITEPARSER_DIR"/liteparser.h     "$OUT/liteparser/include/"
cp "$LITEPARSER_DIR"/liteparser_internal.h "$OUT/liteparser/include/"
cp "$LITEPARSER_DIR"/parse.h          "$OUT/liteparser/include/"

# ─── summary ──────────────────────────────────────────────────────────
echo "── lifted headers ──"
du -sh "$OUT"/*/include | awk '{printf "  %-40s %s\n", $2, $1}'
echo ""
echo "Total: $(du -sh "$OUT" | cut -f1)"
