#!/usr/bin/env bash
# Prebuild iOS arm64 static libs → ge/prebuilt/ios-arm64/.
#
# Run from the ge repo root. Requires all submodules to be initialized
# (git submodule update --init --recursive). Outputs ten static libs:
#   bgfx, bx, bimg, box2d, lunasvg_ge, plutovg_ge, sqlite3_ge, lz4_ge,
#   liteparser, **ge** (engine itself).
#
# The .a files are committed to ge/prebuilt/ios-arm64/ via Git LFS (see
# ge/.gitattributes). Consumer apps' iOS xcodeproj (generated by
# ge/tools/ios-build/build_project.rb) links against these instead of
# recompiling, cutting per-CI-run compile time substantially.
#
# Refresh workflow: bump ge's vendor submodule SHAs (or edit ge sources),
# then re-run this script + lift-headers.sh, then commit. See
# docs/vendor-prebuilds.md.
#
# Copyright 2026 Marcelo Cantos
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

GE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$GE_ROOT"

OUT_DIR="prebuilt/ios-arm64"
OBJ_DIR="build/prebuilt/ios-arm64"
mkdir -p "$OUT_DIR" "$OBJ_DIR"

SDK_PATH="$(xcrun --sdk iphoneos --show-sdk-path)"
CC="$(xcrun --sdk iphoneos -f clang)"
CXX="$(xcrun --sdk iphoneos -f clang++)"
AR="$(xcrun --sdk iphoneos -f libtool)"

COMMON_FLAGS=(
  -arch arm64
  -isysroot "$SDK_PATH"
  -miphoneos-version-min=16.3
  -O2
  -fvisibility=hidden
)

# Force colour-less diagnostics so the log is greppable.
COMMON_FLAGS+=(-fno-color-diagnostics)

C_STD=(-std=c11)
CXX_STD=(-std=c++20)
CXX17_STD=(-std=c++17)

VENDOR="vendor/github.com"
BX_DIR="$VENDOR/bkaradzic/bx"
BIMG_DIR="$VENDOR/bkaradzic/bimg"
BGFX_DIR="$VENDOR/bkaradzic/bgfx"
BOX2D_DIR="$VENDOR/erincatto/box2d"
LUNASVG_DIR="$VENDOR/sammycage/lunasvg"
PLUTOVG_DIR="$LUNASVG_DIR/plutovg"
LITEPARSER_DIR="$VENDOR/sqliteai/liteparser/src"

# Sanity check — submodules must be initialized. (liteparser is checked
# in directly as plain files, not a submodule.)
for d in "$BX_DIR" "$BIMG_DIR" "$BGFX_DIR" "$BOX2D_DIR" "$LUNASVG_DIR"; do
  if [[ ! -f "$d/.git" && ! -d "$d/.git" ]]; then
    echo "error: $d is not initialized. Run: git submodule update --init --recursive" >&2
    exit 1
  fi
done

# ─── build helpers ────────────────────────────────────────────────────────

# compile_c <out.o> <src.c> [extra flags...]
compile_c() {
  local out="$1" src="$2"; shift 2
  mkdir -p "$(dirname "$out")"
  "$CC" "${COMMON_FLAGS[@]}" "${C_STD[@]}" "$@" -c "$src" -o "$out"
}

# compile_cxx <out.o> <src.cpp> [extra flags...] — uses C++20 + lib-specific flags.
compile_cxx() {
  local out="$1" src="$2"; shift 2
  mkdir -p "$(dirname "$out")"
  "$CXX" "${COMMON_FLAGS[@]}" "${CXX_STD[@]}" "$@" -c "$src" -o "$out"
}

# compile_cxx17 <out.o> <src.cpp> [extra flags...]
compile_cxx17() {
  local out="$1" src="$2"; shift 2
  mkdir -p "$(dirname "$out")"
  "$CXX" "${COMMON_FLAGS[@]}" "${CXX17_STD[@]}" "$@" -c "$src" -o "$out"
}

# archive <out.a> <obj1> <obj2>...
archive() {
  local out="$1"; shift
  rm -f "$out"
  "$AR" -static -o "$out" "$@"
}

# ─── bx ───────────────────────────────────────────────────────────────────
echo "── bx (amalgamated) ──"
BX_OBJ="$OBJ_DIR/bx/amalgamated.o"
compile_cxx "$BX_OBJ" "$BX_DIR/src/amalgamated.cpp" \
  -I"$BX_DIR/include" -I"$BX_DIR/include/compat/ios" -I"$BX_DIR/3rdparty" \
  -DBX_CONFIG_DEBUG=0
archive "$OUT_DIR/libbx.a" "$BX_OBJ"

# ─── bimg ─────────────────────────────────────────────────────────────────
echo "── bimg (image.cpp + image_gnf.cpp) ──"
BIMG_OBJS=()
for src in "$BIMG_DIR/src/image.cpp" "$BIMG_DIR/src/image_gnf.cpp"; do
  obj="$OBJ_DIR/bimg/$(basename "${src%.cpp}").o"
  compile_cxx "$obj" "$src" \
    -I"$BIMG_DIR/include" -I"$BIMG_DIR/3rdparty" -I"$BIMG_DIR/3rdparty/astc-encoder/include" \
    -I"$BX_DIR/include" -I"$BX_DIR/include/compat/ios" \
    -DBX_CONFIG_DEBUG=0 -DBIMG_CONFIG_DECODE_ENABLE=0
  BIMG_OBJS+=("$obj")
done
archive "$OUT_DIR/libbimg.a" "${BIMG_OBJS[@]}"

# ─── bgfx ─────────────────────────────────────────────────────────────────
echo "── bgfx (amalgamated, ObjC++ for Metal) ──"
BGFX_OBJ="$OBJ_DIR/bgfx/amalgamated.o"
mkdir -p "$(dirname "$BGFX_OBJ")"
"$CXX" "${COMMON_FLAGS[@]}" "${CXX_STD[@]}" -ObjC++ \
  -I"$BGFX_DIR/include" -I"$BGFX_DIR/3rdparty" -I"$BGFX_DIR/3rdparty/khronos" -I"$BGFX_DIR/src" \
  -I"$BX_DIR/include" -I"$BX_DIR/include/compat/ios" \
  -I"$BIMG_DIR/include" \
  -DBX_CONFIG_DEBUG=0 -DBGFX_CONFIG_RENDERER_METAL=1 \
  -c "$BGFX_DIR/src/amalgamated.cpp" -o "$BGFX_OBJ"
archive "$OUT_DIR/libbgfx.a" "$BGFX_OBJ"

# ─── box2d ────────────────────────────────────────────────────────────────
echo "── box2d ──"
BOX2D_OBJS=()
for src in "$BOX2D_DIR"/src/*.c; do
  obj="$OBJ_DIR/box2d/$(basename "${src%.c}").o"
  compile_c "$obj" "$src" \
    -I"$BOX2D_DIR/include" -I"$BOX2D_DIR/src" \
    -Wno-everything
  BOX2D_OBJS+=("$obj")
done
archive "$OUT_DIR/libbox2d.a" "${BOX2D_OBJS[@]}"

# ─── lunasvg ──────────────────────────────────────────────────────────────
echo "── lunasvg ──"
LUNASVG_OBJS=()
for src in "$LUNASVG_DIR"/source/*.cpp; do
  obj="$OBJ_DIR/lunasvg/$(basename "${src%.cpp}").o"
  compile_cxx17 "$obj" "$src" \
    -I"$LUNASVG_DIR/include" -I"$LUNASVG_DIR/source" -I"$PLUTOVG_DIR/include" \
    -DLUNASVG_BUILD -DLUNASVG_BUILD_STATIC -DPLUTOVG_BUILD_STATIC \
    -Wno-everything
  LUNASVG_OBJS+=("$obj")
done
archive "$OUT_DIR/liblunasvg_ge.a" "${LUNASVG_OBJS[@]}"

# ─── plutovg ──────────────────────────────────────────────────────────────
echo "── plutovg ──"
PLUTOVG_OBJS=()
for src in "$PLUTOVG_DIR"/source/*.c; do
  obj="$OBJ_DIR/plutovg/$(basename "${src%.c}").o"
  compile_c "$obj" "$src" \
    -I"$PLUTOVG_DIR/include" -I"$PLUTOVG_DIR/source" \
    -DPLUTOVG_BUILD -DPLUTOVG_BUILD_STATIC \
    -Wno-everything
  PLUTOVG_OBJS+=("$obj")
done
archive "$OUT_DIR/libplutovg_ge.a" "${PLUTOVG_OBJS[@]}"

# ─── liteparser ───────────────────────────────────────────────────────────
echo "── liteparser ──"
LITEPARSER_OBJS=()
for src in "$LITEPARSER_DIR/arena.c" "$LITEPARSER_DIR/liteparser.c" \
           "$LITEPARSER_DIR/lp_tokenize.c" "$LITEPARSER_DIR/lp_unparse.c" \
           "$LITEPARSER_DIR/parse.c"; do
  obj="$OBJ_DIR/liteparser/$(basename "${src%.c}").o"
  compile_c "$obj" "$src" -I"$LITEPARSER_DIR" -Wno-everything
  LITEPARSER_OBJS+=("$obj")
done
archive "$OUT_DIR/libliteparser.a" "${LITEPARSER_OBJS[@]}"

# ─── sqlite3 (vendored amalgamation, vendor/src/sqlite3.c) ────────────────
echo "── sqlite3 ──"
SQLITE_OBJ="$OBJ_DIR/sqlite3/sqlite3.o"
compile_c "$SQLITE_OBJ" "vendor/src/sqlite3.c" \
  -I vendor/include \
  -DSQLITE_ENABLE_SESSION -DSQLITE_ENABLE_PREUPDATE_HOOK -DSQLITE_ENABLE_DESERIALIZE \
  -Wno-everything
archive "$OUT_DIR/libsqlite3_ge.a" "$SQLITE_OBJ"

# ─── lz4 (vendored amalgamation, vendor/src/lz4.c) ────────────────────────
echo "── lz4 ──"
LZ4_OBJ="$OBJ_DIR/lz4/lz4.o"
compile_c "$LZ4_OBJ" "vendor/src/lz4.c" -I vendor/include -Wno-everything
archive "$OUT_DIR/liblz4_ge.a" "$LZ4_OBJ"

# ─── libge (engine itself) ────────────────────────────────────────────────
# Source list MUST stay in sync with
# tools/ios-build/build_project.rb's GE_DIRECT_SOURCES (modulo
# src/iap_apple.swift, which stays in the consumer build because Swift
# integration with a static lib needs the consumer's bridging-header
# config). Header search paths mirror build_project.rb's
# HEADER_SEARCH_PATHS (T71 post-lift state). Defines mirror
# GCC_PREPROCESSOR_DEFINITIONS from build_project.rb.
echo "── ge ──"

GE_INCLUDES=(
  -I include
  -I vendor/include
  -I headers/spdlog/include
  -I headers/asio/include
  -I headers/sdl3/include
  -I vendor/sdl3/include
  -I headers/liteparser/include
  -I headers/lunasvg/include
  -I headers/plutovg/include
  -I headers/box2d/include
  -I headers/bx/include
  -I headers/bx/include/compat/ios
  -I headers/bimg/include
  -I headers/bgfx/include
)

GE_DEFINES=(
  -DASIO_STANDALONE
  -DGE_IOS
  -DGE_DIRECT_ONLY
  -DSQLITE_ENABLE_SESSION
  -DSQLITE_ENABLE_PREUPDATE_HOOK
  -DSQLITE_ENABLE_DESERIALIZE
  -DBX_CONFIG_DEBUG=0
  -DBIMG_CONFIG_DECODE_ENABLE=0
  -DLUNASVG_BUILD_STATIC
  -DPLUTOVG_BUILD_STATIC
)

GE_SOURCES=(
  src/Context.cpp
  src/Resource.cpp
  src/FileIO.cpp
  src/FontLoader_apple.mm
  src/BgfxContext.mm
  src/Signal.cpp
  src/SessionHost.mm
  src/sprite.cpp
  src/svg.cpp
  src/png.cpp
  src/text.cpp
  src/button.cpp
  src/sdl_input.cpp
  src/iap.cpp
  src/iap_apple.mm
  src/audio.cpp
  src/audio_apple.mm
  src/log.cpp
  src/log_apple.mm
  src/Immersive_stub.cpp
  src/CutoutInsets_stub.cpp
  src/Attitude_apple.mm
  src/render/DirectRenderHost.mm
  src/render/RefreshRateBoost_apple.mm
  tools/player_orientation_ios.mm
  vendor/src/sqlpipe.cpp
)

GE_OBJS=()
for src in "${GE_SOURCES[@]}"; do
  ext="${src##*.}"
  rel="${src%.*}"
  obj="$OBJ_DIR/ge/${rel//\//_}.o"
  mkdir -p "$(dirname "$obj")"
  case "$ext" in
    cpp|mm)
      "$CXX" "${COMMON_FLAGS[@]}" "${CXX_STD[@]}" \
        "${GE_INCLUDES[@]}" "${GE_DEFINES[@]}" \
        -c "$src" -o "$obj"
      ;;
    c)
      "$CC" "${COMMON_FLAGS[@]}" "${C_STD[@]}" \
        "${GE_INCLUDES[@]}" "${GE_DEFINES[@]}" \
        -c "$src" -o "$obj"
      ;;
    *)
      echo "error: unhandled source extension: $src" >&2
      exit 1
      ;;
  esac
  GE_OBJS+=("$obj")
done
archive "$OUT_DIR/libge.a" "${GE_OBJS[@]}"

# ─── summary ──────────────────────────────────────────────────────────────
echo ""
echo "── prebuilt iOS arm64 vendor libs ──"
ls -lh "$OUT_DIR"/*.a | awk '{printf "  %-30s %s\n", $NF, $5}'

echo ""
echo "Total: $(du -sh "$OUT_DIR" | cut -f1)"
