#!/usr/bin/env bash
# Prebuild static libs for one of ge's supported platforms.
#
# Usage:
#   tools/prebuild.sh <platform>
#
# Where <platform> is one of:
#   ios-arm64             — iOS arm64 device (iphoneos SDK, Metal backend)
#   ios-arm64-simulator   — iOS arm64 simulator (iphonesimulator SDK)
#   android-arm64         — Android arm64 (NDK clang, Vulkan + GLES backends)
#
# Outputs ten static libs (bgfx, bx, bimg, box2d, lunasvg_ge, plutovg_ge,
# sqlite3_ge, lz4_ge, liteparser, ge) into prebuilt/<platform>/, plus a
# manifest.json for staleness detection.
#
# Per-platform differences are confined to the case statement at the top
# (toolchain, flags, output dir, bgfx defines, ge source list). The compile
# body below is identical across platforms — same vendor lib calls, same
# manifest writer.
#
# Refresh workflow: bump a vendor submodule SHA or edit a ge source, re-run
# this script for each affected platform + tools/lift-headers.sh, commit.
# See docs/vendor-prebuilds.md.
#
# Copyright 2026 Marcelo Cantos
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <platform>"           >&2
  echo "  platform: ios-arm64 | ios-arm64-simulator | android-arm64" >&2
  exit 1
fi
PLATFORM="$1"

GE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$GE_ROOT"

OUT_DIR="prebuilt/$PLATFORM"
OBJ_DIR="build/prebuilt/$PLATFORM"
# Wipe stale .d files so write-manifest.py only sees deps from this run.
rm -rf "$OBJ_DIR"
mkdir -p "$OUT_DIR" "$OBJ_DIR"

# ─── platform-specific setup ──────────────────────────────────────────────
# Everything that differs across platforms lives here. The compile body
# below uses these variables and doesn't branch further.
COMMON_FLAGS=(-O2 -fvisibility=hidden -fno-color-diagnostics)
BGFX_AS_OBJC=false
BGFX_DEFINES=()
BX_COMPAT_DIR=
GE_PLATFORM_DEFINE=
GE_PLATFORM_SOURCES=()
SDL_STUB_NEEDED=false   # Android needs a stub SDL_revision.h; Apple gets real one from headers/sdl3.

case "$PLATFORM" in
  ios-arm64|ios-arm64-simulator)
    if [[ "$PLATFORM" == "ios-arm64" ]]; then
      SDK=iphoneos
      COMMON_FLAGS+=(-arch arm64 -miphoneos-version-min=16.3)
    else
      SDK=iphonesimulator
      # Apple Silicon sim ABI: arm64 host but -simulator triple variant.
      COMMON_FLAGS+=(-target arm64-apple-ios16.3-simulator)
    fi
    SDK_PATH="$(xcrun --sdk "$SDK" --show-sdk-path)"
    CC="$(xcrun --sdk "$SDK" -f clang)"
    CXX="$(xcrun --sdk "$SDK" -f clang++)"
    AR="$(xcrun --sdk "$SDK" -f libtool)"
    AR_FLAGS=(-static -o)
    COMMON_FLAGS+=(-isysroot "$SDK_PATH")
    BGFX_AS_OBJC=true   # Metal backend needs ObjC++ for the amalgamated unit.
    BGFX_DEFINES=(-DBGFX_CONFIG_RENDERER_METAL=1)
    BX_COMPAT_DIR=ios
    GE_PLATFORM_DEFINE=-DGE_IOS
    GE_MANIFEST_TARGET=print-direct-ios
    ;;
  android-arm64)
    # Locate NDK: explicit env var, else highest installed.
    if [[ -n "${ANDROID_NDK_HOME:-}" ]]; then
      NDK="$ANDROID_NDK_HOME"
    elif [[ -d "$HOME/Library/Android/sdk/ndk" ]]; then
      NDK="$(ls -d "$HOME"/Library/Android/sdk/ndk/*/ 2>/dev/null | sort -V | tail -1)"
      NDK="${NDK%/}"
    fi
    if [[ -z "${NDK:-}" || ! -d "$NDK" ]]; then
      echo "error: Android NDK not found. Set ANDROID_NDK_HOME or install one under ~/Library/Android/sdk/ndk/." >&2
      exit 1
    fi
    NDK_HOST="$(ls "$NDK/toolchains/llvm/prebuilt" 2>/dev/null | head -1)"
    if [[ -z "$NDK_HOST" ]]; then
      echo "error: no llvm host triple under $NDK/toolchains/llvm/prebuilt." >&2
      exit 1
    fi
    NDK_BIN="$NDK/toolchains/llvm/prebuilt/$NDK_HOST/bin"
    NDK_SYSROOT="$NDK/toolchains/llvm/prebuilt/$NDK_HOST/sysroot"
    CC="$NDK_BIN/clang"
    CXX="$NDK_BIN/clang++"
    AR="$NDK_BIN/llvm-ar"
    AR_FLAGS=(rcs)
    COMMON_FLAGS+=(
      --target=aarch64-none-linux-android26
      --sysroot="$NDK_SYSROOT"
      -fPIC -DANDROID -D__ANDROID__
    )
    BGFX_DEFINES=(
      -DBGFX_CONFIG_MULTITHREADED=0
      -DBGFX_CONFIG_RENDERER_VULKAN=1
      -DBGFX_CONFIG_RENDERER_OPENGLES=31
    )
    BX_COMPAT_DIR=linux
    GE_PLATFORM_DEFINE=-DGE_ANDROID
    GE_MANIFEST_TARGET=print-direct-android
    SDL_STUB_NEEDED=true
    ;;
  *)
    echo "error: unsupported platform '$PLATFORM'" >&2
    echo "  supported: ios-arm64 ios-arm64-simulator android-arm64" >&2
    exit 1
    ;;
esac

echo "── platform: $PLATFORM ──"
echo "   CC:  $CC"
echo "   AR:  $AR"

# Android needs a stub SDL_revision.h (the real one is generated by SDL's
# CMake build at consumer-side configure time). On Apple the real header
# lives in headers/sdl3/include and gets picked up by GE_INCLUDES below.
SDL_STUB_INC=
if $SDL_STUB_NEEDED; then
  SDL_STUB_INC="$OBJ_DIR/sdl3-stub"
  mkdir -p "$SDL_STUB_INC/SDL3"
  cat >"$SDL_STUB_INC/SDL3/SDL_revision.h" <<'EOF'
/* Stub SDL_revision.h for ge prebuild. Consumer's SDL build generates a
 * real one with version metadata; ge never reads this constant. */
#define SDL_REVISION "prebuilt-stub"
EOF
fi

C_STD=(-std=c11)
CXX_STD=(-std=c++20)
CXX17_STD=(-std=c++17)
DEPFLAGS=(-MMD -MP)

VENDOR="vendor/github.com"
BX_DIR="$VENDOR/bkaradzic/bx"
BIMG_DIR="$VENDOR/bkaradzic/bimg"
BGFX_DIR="$VENDOR/bkaradzic/bgfx"
BOX2D_DIR="$VENDOR/erincatto/box2d"
LUNASVG_DIR="$VENDOR/sammycage/lunasvg"
PLUTOVG_DIR="$LUNASVG_DIR/plutovg"
LITEPARSER_DIR="$VENDOR/sqliteai/liteparser/src"

# Sanity check — submodules must be initialised.
for d in "$BX_DIR" "$BIMG_DIR" "$BGFX_DIR" "$BOX2D_DIR" "$LUNASVG_DIR"; do
  if [[ ! -f "$d/.git" && ! -d "$d/.git" ]]; then
    echo "error: $d is not initialised. Run: git submodule update --init --recursive" >&2
    exit 1
  fi
done

# ─── build helpers ────────────────────────────────────────────────────────

compile_c() {
  local out="$1" src="$2"; shift 2
  mkdir -p "$(dirname "$out")"
  "$CC" "${COMMON_FLAGS[@]}" "${C_STD[@]}" "${DEPFLAGS[@]}" -MF "$out.d" \
    "$@" -c "$src" -o "$out"
}

compile_cxx() {
  local out="$1" src="$2"; shift 2
  mkdir -p "$(dirname "$out")"
  "$CXX" "${COMMON_FLAGS[@]}" "${CXX_STD[@]}" "${DEPFLAGS[@]}" -MF "$out.d" \
    "$@" -c "$src" -o "$out"
}

compile_cxx17() {
  local out="$1" src="$2"; shift 2
  mkdir -p "$(dirname "$out")"
  "$CXX" "${COMMON_FLAGS[@]}" "${CXX17_STD[@]}" "${DEPFLAGS[@]}" -MF "$out.d" \
    "$@" -c "$src" -o "$out"
}

archive() {
  local out="$1"; shift
  rm -f "$out"
  "$AR" "${AR_FLAGS[@]}" "$out" "$@"
}

# ─── bx ───────────────────────────────────────────────────────────────────
echo "── bx (amalgamated) ──"
BX_OBJ="$OBJ_DIR/bx/amalgamated.o"
compile_cxx "$BX_OBJ" "$BX_DIR/src/amalgamated.cpp" \
  -I"$BX_DIR/include" -I"$BX_DIR/include/compat/$BX_COMPAT_DIR" -I"$BX_DIR/3rdparty" \
  -DBX_CONFIG_DEBUG=0
archive "$OUT_DIR/libbx.a" "$BX_OBJ"

# ─── bimg ─────────────────────────────────────────────────────────────────
echo "── bimg ──"
BIMG_OBJS=()
for src in "$BIMG_DIR/src/image.cpp" "$BIMG_DIR/src/image_gnf.cpp"; do
  obj="$OBJ_DIR/bimg/$(basename "${src%.cpp}").o"
  compile_cxx "$obj" "$src" \
    -I"$BIMG_DIR/include" -I"$BIMG_DIR/3rdparty" -I"$BIMG_DIR/3rdparty/astc-encoder/include" \
    -I"$BX_DIR/include" -I"$BX_DIR/include/compat/$BX_COMPAT_DIR" \
    -DBX_CONFIG_DEBUG=0 -DBIMG_CONFIG_DECODE_ENABLE=0
  BIMG_OBJS+=("$obj")
done
archive "$OUT_DIR/libbimg.a" "${BIMG_OBJS[@]}"

# ─── bgfx (amalgamated) ───────────────────────────────────────────────────
echo "── bgfx (amalgamated) ──"
BGFX_OBJ="$OBJ_DIR/bgfx/amalgamated.o"
mkdir -p "$(dirname "$BGFX_OBJ")"
BGFX_CFLAGS=(
  "${COMMON_FLAGS[@]}" "${CXX_STD[@]}" "${DEPFLAGS[@]}" -MF "$BGFX_OBJ.d"
  -I"$BGFX_DIR/include" -I"$BGFX_DIR/3rdparty" -I"$BGFX_DIR/3rdparty/khronos" -I"$BGFX_DIR/src"
  -I"$BX_DIR/include" -I"$BX_DIR/include/compat/$BX_COMPAT_DIR"
  -I"$BIMG_DIR/include"
  -DBX_CONFIG_DEBUG=0
  "${BGFX_DEFINES[@]}"
)
if $BGFX_AS_OBJC; then
  BGFX_CFLAGS+=(-ObjC++)
fi
"$CXX" "${BGFX_CFLAGS[@]}" -c "$BGFX_DIR/src/amalgamated.cpp" -o "$BGFX_OBJ"
archive "$OUT_DIR/libbgfx.a" "$BGFX_OBJ"

# ─── box2d ────────────────────────────────────────────────────────────────
echo "── box2d ──"
BOX2D_OBJS=()
for src in "$BOX2D_DIR"/src/*.c; do
  obj="$OBJ_DIR/box2d/$(basename "${src%.c}").o"
  compile_c "$obj" "$src" \
    -I"$BOX2D_DIR/include" -I"$BOX2D_DIR/src" \
    -Wno-everything
  BOX2D_OBJS+=("$obj")
done
archive "$OUT_DIR/libbox2d.a" "${BOX2D_OBJS[@]}"

# ─── lunasvg ──────────────────────────────────────────────────────────────
echo "── lunasvg ──"
LUNASVG_OBJS=()
for src in "$LUNASVG_DIR"/source/*.cpp; do
  obj="$OBJ_DIR/lunasvg/$(basename "${src%.cpp}").o"
  compile_cxx17 "$obj" "$src" \
    -I"$LUNASVG_DIR/include" -I"$LUNASVG_DIR/source" -I"$PLUTOVG_DIR/include" \
    -DLUNASVG_BUILD -DLUNASVG_BUILD_STATIC -DPLUTOVG_BUILD_STATIC \
    -Wno-everything
  LUNASVG_OBJS+=("$obj")
done
archive "$OUT_DIR/liblunasvg_ge.a" "${LUNASVG_OBJS[@]}"

# ─── plutovg ──────────────────────────────────────────────────────────────
echo "── plutovg ──"
PLUTOVG_OBJS=()
for src in "$PLUTOVG_DIR"/source/*.c; do
  obj="$OBJ_DIR/plutovg/$(basename "${src%.c}").o"
  compile_c "$obj" "$src" \
    -I"$PLUTOVG_DIR/include" -I"$PLUTOVG_DIR/source" \
    -DPLUTOVG_BUILD -DPLUTOVG_BUILD_STATIC \
    -Wno-everything
  PLUTOVG_OBJS+=("$obj")
done
archive "$OUT_DIR/libplutovg_ge.a" "${PLUTOVG_OBJS[@]}"

# ─── liteparser ───────────────────────────────────────────────────────────
echo "── liteparser ──"
LITEPARSER_OBJS=()
for src in "$LITEPARSER_DIR/arena.c" "$LITEPARSER_DIR/liteparser.c" \
           "$LITEPARSER_DIR/lp_tokenize.c" "$LITEPARSER_DIR/lp_unparse.c" \
           "$LITEPARSER_DIR/parse.c"; do
  obj="$OBJ_DIR/liteparser/$(basename "${src%.c}").o"
  compile_c "$obj" "$src" -I"$LITEPARSER_DIR" -Wno-everything
  LITEPARSER_OBJS+=("$obj")
done
archive "$OUT_DIR/libliteparser.a" "${LITEPARSER_OBJS[@]}"

# ─── sqlite3 ──────────────────────────────────────────────────────────────
echo "── sqlite3 ──"
SQLITE_OBJ="$OBJ_DIR/sqlite3/sqlite3.o"
compile_c "$SQLITE_OBJ" "vendor/src/sqlite3.c" \
  -I vendor/include \
  -DSQLITE_ENABLE_SESSION -DSQLITE_ENABLE_PREUPDATE_HOOK -DSQLITE_ENABLE_DESERIALIZE \
  -Wno-everything
archive "$OUT_DIR/libsqlite3_ge.a" "$SQLITE_OBJ"

# ─── lz4 ──────────────────────────────────────────────────────────────────
echo "── lz4 ──"
LZ4_OBJ="$OBJ_DIR/lz4/lz4.o"
compile_c "$LZ4_OBJ" "vendor/src/lz4.c" -I vendor/include -Wno-everything
archive "$OUT_DIR/liblz4_ge.a" "$LZ4_OBJ"

# ─── libge (engine itself) ────────────────────────────────────────────────
echo "── ge ──"

# Header search paths match the iOS xcodeproj-gem path
# (tools/ios-build/build_project.rb#header_search_paths) post-T71 header
# lifting — so the same #include landscape works on both platforms.
GE_INCLUDES=(
  -I include
  -I vendor/include
  -I headers/spdlog/include
  -I headers/asio/include
  -I headers/sdl3/include
  -I vendor/sdl3/include
  -I headers/liteparser/include
  -I headers/lunasvg/include
  -I headers/plutovg/include
  -I headers/box2d/include
  -I headers/bx/include
  -I "headers/bx/include/compat/$BX_COMPAT_DIR"
  -I headers/bimg/include
  -I headers/bgfx/include
)
if [[ -n "$SDL_STUB_INC" ]]; then
  GE_INCLUDES+=(-I "$SDL_STUB_INC")
fi

GE_DEFINES=(
  -DASIO_STANDALONE
  "$GE_PLATFORM_DEFINE"
  -DGE_DIRECT_ONLY
  -DSQLITE_ENABLE_SESSION
  -DSQLITE_ENABLE_PREUPDATE_HOOK
  -DSQLITE_ENABLE_DESERIALIZE
  -DBX_CONFIG_DEBUG=0
  -DBIMG_CONFIG_DECODE_ENABLE=0
  -DLUNASVG_BUILD_STATIC
  -DPLUTOVG_BUILD_STATIC
  "${BGFX_DEFINES[@]}"
)

# ge source list — extracted from the canonical manifest at
# tools/ge-sources.mk so this script and Module.mk stay in sync.
# GE_MANIFEST_TARGET was selected per-platform above.
mapfile -t GE_SOURCES < <(make -s -f tools/ge-sources.mk "$GE_MANIFEST_TARGET")
if [[ ${#GE_SOURCES[@]} -eq 0 ]]; then
  echo "error: tools/ge-sources.mk produced no sources for $GE_MANIFEST_TARGET" >&2
  exit 1
fi

GE_OBJS=()
for src in "${GE_SOURCES[@]}"; do
  ext="${src##*.}"
  rel="${src%.*}"
  obj="$OBJ_DIR/ge/${rel//\//_}.o"
  mkdir -p "$(dirname "$obj")"
  case "$ext" in
    cpp|mm)
      # On Apple .mm is ObjC++; on Android (no ObjC) treat .mm as plain C++.
      lang_flag=()
      if [[ "$ext" == "mm" && "$PLATFORM" == "android-arm64" ]]; then
        lang_flag=(-x c++)
      fi
      "$CXX" "${COMMON_FLAGS[@]}" "${CXX_STD[@]}" "${DEPFLAGS[@]}" -MF "$obj.d" \
        "${lang_flag[@]}" "${GE_INCLUDES[@]}" "${GE_DEFINES[@]}" \
        -c "$src" -o "$obj"
      ;;
    c)
      "$CC" "${COMMON_FLAGS[@]}" "${C_STD[@]}" "${DEPFLAGS[@]}" -MF "$obj.d" \
        "${GE_INCLUDES[@]}" "${GE_DEFINES[@]}" \
        -c "$src" -o "$obj"
      ;;
    *)
      echo "error: unhandled source extension: $src" >&2
      exit 1
      ;;
  esac
  GE_OBJS+=("$obj")
done
archive "$OUT_DIR/libge.a" "${GE_OBJS[@]}"

# ─── manifest ─────────────────────────────────────────────────────────────
echo ""
echo "── manifest ──"
python3 tools/write-manifest.py --platform "$PLATFORM"

# ─── summary ──────────────────────────────────────────────────────────────
echo ""
echo "── prebuilt $PLATFORM vendor libs ──"
ls -lh "$OUT_DIR"/*.a | awk '{printf "  %-30s %s\n", $NF, $5}'
echo ""
echo "Total: $(du -sh "$OUT_DIR" | cut -f1)"
