// Copyright 2026 Marcelo Cantos
// SPDX-License-Identifier: Apache-2.0
//
// 🎯T170 Gesture-hint timeline core — clip choreography and playback.
// 🎯T179 Multi-segment authoring + per-phase timing.
//
// Choreography convention shared by the single-finger clips: the hand
// fades in while approaching the touch point from a small below-right
// offset (where a right hand naturally enters), presses, performs the
// gesture, lifts, and fades out with a slight drift. Contact steps true
// exactly when press reaches 1 and steps false at the moment the lift
// begins — press relaxing after release matches how a real finger
// leaves the glass. All times are seconds at Params.speed == 1.

#include <ge/hint.h>

#include <algorithm>
#include <cmath>
#include <functional>

namespace ge::hint {

namespace {

constexpr la::float2 kEnterOffset{0.10f, 0.14f};  // below-right, unit space

float applyEase(Ease e, float u) {
    switch (e) {
        case Ease::Step:   return u < 1.0f ? 0.0f : 1.0f;
        case Ease::Linear: return u;
        case Ease::InOut:  return u * u * (3.0f - 2.0f * u);
        case Ease::Out:    return 1.0f - (1.0f - u) * (1.0f - u) * (1.0f - u);
        case Ease::In:     return u * u * u;
    }
    return u;
}

la::float2 lerp2(la::float2 a, la::float2 b, float u) { return a + (b - a) * u; }

// Track-building shorthand so the choreography below reads as a table.
struct TB {
    std::vector<Key> keys;
    void k(float t, la::float2 pos, float press, float opacity, bool contact,
           Ease ease = Ease::InOut) {
        keys.push_back({t, pos, contact, press, opacity, ease});
    }
};

Clip singleFinger(std::vector<Key> keys, float duration, std::vector<TagEvent> tags) {
    Clip c;
    c.duration = duration;
    c.tracks.push_back({std::move(keys)});
    c.tags = std::move(tags);
    return c;
}

// Two-finger clips: track 0 starts at `a`, track 1 at `b`; positions are
// generated by `posAt(i, u)` for eased progress u in [0,1] over the
// active phase. Arc motion needs intermediate keys (two keys would lerp
// along the chord), so the active phase is subdivided.
Clip twoFinger(const std::function<la::float2(int finger, float u)>& posAt,
               PhaseTiming timing) {
    const float tApproach = std::max(0.0f, timing.approach);
    const float tDown     = tApproach + std::max(0.0f, timing.pressIn);
    const float tMoveE    = tDown + std::max(0.0f, timing.stroke);
    const float tLift     = tMoveE + std::max(0.0f, timing.hold);
    const float tUp       = tLift + std::max(0.0f, timing.pressOut);
    const float tEnd      = tUp + std::max(0.0f, timing.exit);
    Clip c;
    c.duration = tEnd + 0.05f;
    for (int i = 0; i < 2; ++i) {
        TB tb;
        la::float2 start = posAt(i, 0), end = posAt(i, 1);
        la::float2 off   = (i == 0 ? la::float2{-0.06f, 0.10f} : la::float2{0.06f, -0.10f});
        tb.k(0.00f, start + off, 0, 0, false);
        tb.k(tApproach, start, 0, 1, false, Ease::Out);
        tb.k(tDown, start, 1, 1, true);
        constexpr int kSteps = 8;
        for (int j = 1; j < kSteps; ++j) {
            float seg = float(j) / kSteps;
            float t   = tDown + (tMoveE - tDown) * seg;
            tb.k(t, posAt(i, applyEase(Ease::InOut, seg)), 1, 1, true, Ease::Linear);
        }
        // Final move key: contact holds through any hold gap, then lift.
        if (tLift > tMoveE) {
            tb.k(tMoveE, end, 1, 1, true, Ease::Linear);
            tb.k(tLift, end, 1, 1, false);
        } else {
            tb.k(tMoveE, end, 1, 1, false, Ease::Linear);
        }
        tb.k(tUp, end, 0, 1, false, Ease::Out);
        tb.k(tEnd, end + off * 0.4f, 0, 0, false, Ease::In);
        c.tracks.push_back({std::move(tb.keys)});
    }
    c.tags = {{tDown, tag::pinchStart}, {tLift, tag::pinchEnd}};
    return c;
}

// Sample one track at clip time t.
PointerState sampleTrack(const std::vector<Key>& keys, float t) {
    PointerState s;
    if (keys.empty()) return s;
    if (t <= keys.front().t) {
        const Key& k = keys.front();
        return {k.pos, k.contact, k.press, k.opacity};
    }
    for (size_t i = 1; i < keys.size(); ++i) {
        if (t < keys[i].t) {
            const Key& a = keys[i - 1];
            const Key& b = keys[i];
            float u = applyEase(b.ease, (t - a.t) / (b.t - a.t));
            return {lerp2(a.pos, b.pos, u),
                    a.contact,  // contact steps at key times
                    a.press + (b.press - a.press) * u,
                    a.opacity + (b.opacity - a.opacity) * u};
        }
    }
    const Key& k = keys.back();
    return {k.pos, k.contact, k.press, k.opacity};
}

}  // namespace

// ── 🎯T179 public authoring ─────────────────────────────────────────

Clip makeContactClip(std::span<const la::float2> waypoints,
                     PhaseTiming timing,
                     Ease strokeEase) {
    if (waypoints.empty()) {
        // Degenerate: empty fade at origin so Player stays safe.
        return singleFinger({{0, {0.5f, 0.5f}, false, 0, 0, Ease::Linear}}, 0.01f, {});
    }

    const la::float2 first = waypoints.front();
    const la::float2 last  = waypoints.back();

    const float tApproach = std::max(0.0f, timing.approach);
    const float tContact  = tApproach + std::max(0.0f, timing.pressIn);
    const float tStrokeE  = tContact + std::max(0.0f, timing.stroke);
    const float tLift     = tStrokeE + std::max(0.0f, timing.hold);
    const float tUp       = tLift + std::max(0.0f, timing.pressOut);
    const float tExitEnd  = tUp + std::max(0.0f, timing.exit);

    TB tb;
    tb.k(0.00f, first + kEnterOffset, 0, 0, false);
    tb.k(tApproach, first, 0, 1, false, Ease::Out);
    tb.k(tContact, first, 1, 1, true);

    const int n = static_cast<int>(waypoints.size());
    bool liftKeyed = false;
    if (n == 1 || timing.stroke <= 0.0f) {
        // Stationary contact (tap / hold). Dwell, then lift.
        if (tLift > tContact) {
            // Hold key keeps contact true through the dwell segment.
            // Lift is the next key below.
        }
    } else {
        // Multi-waypoint chain: contact stays true for every intermediate
        // and for the last waypoint until lift.
        for (int i = 1; i < n; ++i) {
            const float u  = float(i) / float(n - 1);
            const float ti = tContact + timing.stroke * u;
            const bool  isLast = (i == n - 1);
            if (isLast && tLift <= ti + 1e-6f) {
                // Stroke end coincides with lift — contact ends here.
                tb.k(ti, waypoints[static_cast<size_t>(i)], 1, 1, false, strokeEase);
                liftKeyed = true;
            } else {
                tb.k(ti, waypoints[static_cast<size_t>(i)], 1, 1, true, strokeEase);
            }
        }
    }

    // Lift: contact steps false (if not already keyed on the last stroke).
    if (!liftKeyed) tb.k(tLift, last, 1, 1, false);
    la::float2 drift = last;
    if (n >= 2) drift = last + (last - first) * 0.06f;
    tb.k(tUp, drift, 0, 1, false, Ease::Out);
    tb.k(tExitEnd, last + kEnterOffset * 0.4f, 0, 0, false, Ease::In);

    std::vector<TagEvent> tags;
    tags.push_back({tContact, tag::contact});
    if (n >= 2 && timing.stroke > 0.0f) {
        const float apexT = tContact + timing.stroke * 0.5f;
        tags.push_back({apexT, tag::apex});
    }
    tags.push_back({tLift, tag::release});

    return singleFinger(std::move(tb.keys), tExitEnd + 0.15f, std::move(tags));
}

Clip makeTapClip(la::float2 at, PhaseTiming timing) {
    // Match pre-T179 tap: contact 0.48, release 0.58, exit ~1.10, dur 1.25.
    PhaseTiming t = timing;
    if (t.stroke == 1.00f && t.hold == 0.05f) {
        // Defaults → stock tap timings.
        t.approach = 0.35f;
        t.pressIn  = 0.13f;  // contact at 0.48
        t.stroke   = 0.0f;
        t.hold     = 0.10f;  // release at 0.58
        t.pressOut = 0.14f;
        t.exit     = 0.38f;
    }
    return makeContactClip(std::span<const la::float2>(&at, 1), t, Ease::InOut);
}

Clip makeDoubleTapClip(la::float2 at, PhaseTiming timing) {
    // Two contact pulses with a partial mid-lift; still one approach/exit.
    const float tApproach = std::max(0.0f, timing.approach > 0 ? timing.approach : 0.35f);
    const float t0 = tApproach + 0.10f;  // first contact ~0.45
    TB tb;
    tb.k(0.00f, at + kEnterOffset, 0, 0, false);
    tb.k(tApproach, at, 0, 1, false, Ease::Out);
    tb.k(t0, at, 1, 1, true);
    tb.k(t0 + 0.10f, at, 1, 1, false);
    tb.k(t0 + 0.18f, at, 0.15f, 1, false, Ease::Out);
    tb.k(t0 + 0.27f, at, 1, 1, true);
    tb.k(t0 + 0.37f, at, 1, 1, false);
    tb.k(t0 + 0.50f, at, 0, 1, false, Ease::Out);
    const float tExit = t0 + 0.85f;
    tb.k(tExit, at + kEnterOffset * 0.4f, 0, 0, false, Ease::In);
    return singleFinger(std::move(tb.keys), tExit + 0.15f,
                        {{t0, tag::contact},
                         {t0 + 0.10f, tag::release},
                         {t0 + 0.27f, tag::contact},
                         {t0 + 0.37f, tag::release}});
}

Clip makeLongPressClip(la::float2 at, PhaseTiming timing) {
    const float tApproach = std::max(0.0f, timing.approach > 0 ? timing.approach : 0.35f);
    const float tContact  = tApproach + 0.10f;  // ~0.45
    const float hold      = timing.stroke > 0.5f ? timing.stroke : 1.00f;
    const float tLift     = tContact + hold;     // ~1.45
    TB tb;
    tb.k(0.00f, at + kEnterOffset, 0, 0, false);
    tb.k(tApproach, at, 0, 1, false, Ease::Out);
    tb.k(tContact, at, 1, 1, true);
    tb.k(tContact + hold * 0.55f, at, 0.92f, 1, true);  // subtle settle
    tb.k(tLift, at, 1, 1, true);
    tb.k(tLift, at, 1, 1, false);
    tb.k(tLift + 0.15f, at, 0, 1, false, Ease::Out);
    const float tExit = tLift + 0.50f;
    tb.k(tExit, at + kEnterOffset * 0.4f, 0, 0, false, Ease::In);
    return singleFinger(std::move(tb.keys), tExit + 0.15f,
                        {{tContact, tag::contact},
                         {tContact + 0.20f, tag::holdStart},
                         {tLift, tag::release}});
}

Clip makePinchZoomClip(la::float2 a, la::float2 b, PhaseTiming timing) {
    PhaseTiming t = timing;
    if (t.stroke == 1.00f) t.stroke = 0.60f;  // stock pinch motion window
    la::float2 center = (a + b) * 0.5f;
    return twoFinger(
        [=](int i, float u) {
            la::float2 target = i == 0 ? a : b;
            return lerp2(lerp2(center, target, 0.3f), target, u);
        },
        t);
}

Clip makePinchRotateClip(la::float2 a, la::float2 b, PhaseTiming timing) {
    PhaseTiming t = timing;
    if (t.stroke == 1.00f) t.stroke = 0.60f;
    la::float2 center = (a + b) * 0.5f;
    la::float2 r0     = a - center;
    const float sweep = 75.0f * 3.14159265f / 180.0f;
    return twoFinger(
        [=](int i, float u) {
            float base = i == 0 ? 0.0f : 3.14159265f;
            float ang  = base + sweep * u;
            float ca = std::cos(ang), sa = std::sin(ang);
            return center + la::float2{r0.x * ca - r0.y * sa, r0.x * sa + r0.y * ca};
        },
        t);
}

Clip makeClip(Kind kind, const Params& params) {
    switch (kind) {
        case Kind::Tap:
            return makeTapClip(params.from);
        case Kind::DoubleTap:
            return makeDoubleTapClip(params.from);
        case Kind::LongPress:
            return makeLongPressClip(params.from);
        case Kind::Swipe: {
            PhaseTiming t;
            t.stroke = 0.40f;
            t.hold   = 0.0f;
            la::float2 wps[] = {params.from, params.to};
            return makeContactClip(wps, t, Ease::Out);
        }
        case Kind::Drag: {
            PhaseTiming t;  // defaults match pre-T179 drag
            la::float2 wps[] = {params.from, params.to};
            return makeContactClip(wps, t, Ease::InOut);
        }
        case Kind::PinchZoom:
            return makePinchZoomClip(params.from, params.to);
        case Kind::PinchRotate:
            return makePinchRotateClip(params.from, params.to);
    }
    return makeTapClip(params.from);
}

Player::Player(Kind kind, Params params)
    : kind_(kind), params_(params), clip_(makeClip(kind, params)) {
    states_.resize(clip_.tracks.size());
    sample();
}

Player::Player(Clip clip, Params params)
    : kind_(Kind::Drag), params_(params), clip_(std::move(clip)) {
    states_.resize(clip_.tracks.size());
    sample();
}

void Player::update(float dt) {
    started_ = true;
    const float prev = t_;
    t_ += std::max(0.0f, dt) * params_.speed;

    // Wrap through as many loop cycles as this step spans (a large dt
    // after a stall stays correct), counting wraps for tag replay.
    const float cycle = clip_.duration + std::max(0.0f, params_.loopGap);
    int         wraps = 0;
    if (params_.loop && cycle > 0.0f)
        while (t_ >= cycle) {
            t_ -= cycle;
            ++wraps;
        }

    // Sample *before* firing so tag callbacks read post-step pointer
    // state — a `contact` handler sees contact == true at the pointer's
    // touch position.
    sample();

    if (wraps == 0) {
        fireTags(prev, std::min(t_, clip_.duration));
    } else {
        fireTags(prev, clip_.duration);
        for (int i = 1; i < wraps; ++i) fireTags(0.0f, clip_.duration);
        fireTags(0.0f, std::min(t_, clip_.duration));
    }
}

void Player::reset() {
    t_       = 0.0f;
    started_ = false;
    sample();
}

bool Player::active() const {
    return params_.loop || t_ < clip_.duration;
}

float Player::duration() const {
    return params_.speed > 0.0f ? clip_.duration / params_.speed : clip_.duration;
}

void Player::sample() {
    // In the loop gap (t_ > duration) every clip has faded out; sampling
    // clamped at duration holds that blank state.
    float ts = std::min(t_, clip_.duration);
    for (size_t i = 0; i < clip_.tracks.size(); ++i)
        states_[i] = sampleTrack(clip_.tracks[i].keys, ts);
}

void Player::fireTags(float from, float to) {
    if (!onTag || to < from) return;
    for (const TagEvent& e : clip_.tags)
        if (e.t > from && e.t <= to) onTag(e.tag);
}

}  // namespace ge::hint
