// Copyright 2026 Marcelo Cantos
// SPDX-License-Identifier: Apache-2.0
//
// 🎯T170 Gesture-hint timeline core — clip choreography and playback.
//
// Choreography convention shared by the single-finger clips: the hand
// fades in while approaching the touch point from a small below-right
// offset (where a right hand naturally enters), presses, performs the
// gesture, lifts, and fades out with a slight drift. Contact steps true
// exactly when press reaches 1 and steps false at the moment the lift
// begins — press relaxing after release matches how a real finger
// leaves the glass. All times are seconds at Params.speed == 1.

#include <ge/hint.h>

#include <algorithm>
#include <cmath>

namespace ge::hint {

namespace {

constexpr la::float2 kEnterOffset{0.10f, 0.14f};  // below-right, unit space

float applyEase(Ease e, float u) {
    switch (e) {
        case Ease::Step:   return u < 1.0f ? 0.0f : 1.0f;
        case Ease::Linear: return u;
        case Ease::InOut:  return u * u * (3.0f - 2.0f * u);
        case Ease::Out:    return 1.0f - (1.0f - u) * (1.0f - u) * (1.0f - u);
        case Ease::In:     return u * u * u;
    }
    return u;
}

la::float2 lerp2(la::float2 a, la::float2 b, float u) { return a + (b - a) * u; }

// Track-building shorthand so the choreography below reads as a table.
struct TB {
    std::vector<Key> keys;
    void k(float t, la::float2 pos, float press, float opacity, bool contact,
           Ease ease = Ease::InOut) {
        keys.push_back({t, pos, contact, press, opacity, ease});
    }
};

// Shared entry/exit flourish for one-finger gestures: fade-in approach
// to `at` finishing at tApproach, and fade-out drift starting from the
// caller's last key.
void enter(TB& tb, la::float2 at) {
    tb.k(0.00f, at + kEnterOffset, 0, 0, false);
    tb.k(0.35f, at, 0, 1, false, Ease::Out);
}
void exit(TB& tb, la::float2 from, float tEnd) {
    tb.k(tEnd, from + kEnterOffset * 0.4f, 0, 0, false, Ease::In);
}

Clip singleFinger(std::vector<Key> keys, float duration, std::vector<TagEvent> tags) {
    Clip c;
    c.duration = duration;
    c.tracks.push_back({std::move(keys)});
    c.tags = std::move(tags);
    return c;
}

Clip makeTap(const Params& p) {
    TB tb;
    enter(tb, p.from);
    tb.k(0.48f, p.from, 1, 1, true);              // press down
    tb.k(0.58f, p.from, 1, 1, false);             // hold; lift begins here
    tb.k(0.72f, p.from, 0, 1, false, Ease::Out);  // finger back up
    exit(tb, p.from, 1.10f);
    return singleFinger(std::move(tb.keys), 1.25f,
                        {{0.48f, tag::contact}, {0.58f, tag::release}});
}

Clip makeDoubleTap(const Params& p) {
    TB tb;
    enter(tb, p.from);
    tb.k(0.45f, p.from, 1, 1, true);
    tb.k(0.55f, p.from, 1, 1, false);
    tb.k(0.63f, p.from, 0.15f, 1, false, Ease::Out);  // partial lift between taps
    tb.k(0.72f, p.from, 1, 1, true);
    tb.k(0.82f, p.from, 1, 1, false);
    tb.k(0.95f, p.from, 0, 1, false, Ease::Out);
    exit(tb, p.from, 1.30f);
    return singleFinger(std::move(tb.keys), 1.45f,
                        {{0.45f, tag::contact},
                         {0.55f, tag::release},
                         {0.72f, tag::contact},
                         {0.82f, tag::release}});
}

Clip makeLongPress(const Params& p) {
    TB tb;
    enter(tb, p.from);
    tb.k(0.45f, p.from, 1, 1, true);
    tb.k(1.00f, p.from, 0.92f, 1, true);   // subtle settle while holding
    tb.k(1.35f, p.from, 1, 1, true);
    tb.k(1.45f, p.from, 1, 1, false);      // lift begins
    tb.k(1.60f, p.from, 0, 1, false, Ease::Out);
    exit(tb, p.from, 1.95f);
    return singleFinger(std::move(tb.keys), 2.10f,
                        {{0.45f, tag::contact},
                         {0.65f, tag::holdStart},
                         {1.45f, tag::release}});
}

Clip makeStroke(const Params& p, bool fast) {
    // Swipe: quick flick, easing out (fast start, gentle stop).
    // Drag: deliberate InOut glide, twice the stroke time.
    const float tDown    = 0.45f;
    const float tStrokeE = fast ? 0.85f : 1.45f;
    const float tLift    = fast ? 0.85f : 1.50f;
    TB tb;
    enter(tb, p.from);
    tb.k(tDown, p.from, 1, 1, true);
    tb.k(tStrokeE, p.to, 1, 1, tLift > tStrokeE, fast ? Ease::Out : Ease::InOut);
    if (tLift > tStrokeE) tb.k(tLift, p.to, 1, 1, false);
    tb.k(tLift + 0.15f, p.to + (p.to - p.from) * 0.06f, 0, 1, false, Ease::Out);
    exit(tb, p.to, tLift + 0.50f);
    const float apexT = tDown + (tStrokeE - tDown) * 0.5f;
    return singleFinger(std::move(tb.keys), tLift + 0.65f,
                        {{tDown, tag::contact}, {apexT, tag::apex}, {tLift, tag::release}});
}

// Two-finger clips: track 0 starts at `a`, track 1 at `b`; positions are
// generated by `posAt(i, u)` for eased progress u in [0,1] over the
// active phase. Arc motion needs intermediate keys (two keys would lerp
// along the chord), so the active phase is subdivided.
Clip twoFinger(const std::function<la::float2(int finger, float u)>& posAt) {
    const float tDown = 0.45f, tMoveE = 1.05f, tLift = 1.10f;
    Clip c;
    c.duration = 1.60f;
    for (int i = 0; i < 2; ++i) {
        TB tb;
        la::float2 start = posAt(i, 0), end = posAt(i, 1);
        la::float2 off   = (i == 0 ? la::float2{-0.06f, 0.10f} : la::float2{0.06f, -0.10f});
        tb.k(0.00f, start + off, 0, 0, false);
        tb.k(0.35f, start, 0, 1, false, Ease::Out);
        tb.k(tDown, start, 1, 1, true);
        constexpr int kSteps = 8;
        for (int j = 1; j <= kSteps; ++j) {
            float seg = float(j) / kSteps;
            float t   = tDown + (tMoveE - tDown) * seg;
            tb.k(t, posAt(i, applyEase(Ease::InOut, seg)), 1, 1, true, Ease::Linear);
        }
        tb.k(tLift, end, 1, 1, false);
        tb.k(tLift + 0.15f, end, 0, 1, false, Ease::Out);
        tb.k(1.55f, end + off * 0.4f, 0, 0, false, Ease::In);
        c.tracks.push_back({std::move(tb.keys)});
    }
    c.tags = {{tDown, tag::pinchStart}, {tLift, tag::pinchEnd}};
    return c;
}

Clip makePinchZoom(const Params& p) {
    la::float2 center = (p.from + p.to) * 0.5f;
    return twoFinger([=](int i, float u) {
        la::float2 target = i == 0 ? p.from : p.to;
        // Spread outward: start close to the center, end at from/to.
        return lerp2(lerp2(center, target, 0.3f), target, u);
    });
}

Clip makePinchRotate(const Params& p) {
    la::float2 center = (p.from + p.to) * 0.5f;
    la::float2 r0     = p.from - center;
    const float sweep = 75.0f * 3.14159265f / 180.0f;
    return twoFinger([=](int i, float u) {
        float base = i == 0 ? 0.0f : 3.14159265f;  // fingers oppose across center
        float ang  = base + sweep * u;
        float ca = std::cos(ang), sa = std::sin(ang);
        return center + la::float2{r0.x * ca - r0.y * sa, r0.x * sa + r0.y * ca};
    });
}

// Sample one track at clip time t.
PointerState sampleTrack(const std::vector<Key>& keys, float t) {
    PointerState s;
    if (keys.empty()) return s;
    if (t <= keys.front().t) {
        const Key& k = keys.front();
        return {k.pos, k.contact, k.press, k.opacity};
    }
    for (size_t i = 1; i < keys.size(); ++i) {
        if (t < keys[i].t) {
            const Key& a = keys[i - 1];
            const Key& b = keys[i];
            float u = applyEase(b.ease, (t - a.t) / (b.t - a.t));
            return {lerp2(a.pos, b.pos, u),
                    a.contact,  // contact steps at key times
                    a.press + (b.press - a.press) * u,
                    a.opacity + (b.opacity - a.opacity) * u};
        }
    }
    const Key& k = keys.back();
    return {k.pos, k.contact, k.press, k.opacity};
}

}  // namespace

Clip makeClip(Kind kind, const Params& params) {
    switch (kind) {
        case Kind::Tap:         return makeTap(params);
        case Kind::DoubleTap:   return makeDoubleTap(params);
        case Kind::LongPress:   return makeLongPress(params);
        case Kind::Swipe:       return makeStroke(params, /*fast=*/true);
        case Kind::Drag:        return makeStroke(params, /*fast=*/false);
        case Kind::PinchZoom:   return makePinchZoom(params);
        case Kind::PinchRotate: return makePinchRotate(params);
    }
    return makeTap(params);
}

Player::Player(Kind kind, Params params)
    : kind_(kind), params_(params), clip_(makeClip(kind, params)) {
    states_.resize(clip_.tracks.size());
    sample();
}

void Player::update(float dt) {
    started_ = true;
    const float prev = t_;
    t_ += std::max(0.0f, dt) * params_.speed;

    // Wrap through as many loop cycles as this step spans (a large dt
    // after a stall stays correct), counting wraps for tag replay.
    const float cycle = clip_.duration + std::max(0.0f, params_.loopGap);
    int         wraps = 0;
    if (params_.loop && cycle > 0.0f)
        while (t_ >= cycle) {
            t_ -= cycle;
            ++wraps;
        }

    // Sample *before* firing so tag callbacks read post-step pointer
    // state — a `contact` handler sees contact == true at the pointer's
    // touch position.
    sample();

    if (wraps == 0) {
        fireTags(prev, std::min(t_, clip_.duration));
    } else {
        fireTags(prev, clip_.duration);
        for (int i = 1; i < wraps; ++i) fireTags(0.0f, clip_.duration);
        fireTags(0.0f, std::min(t_, clip_.duration));
    }
}

void Player::reset() {
    t_       = 0.0f;
    started_ = false;
    sample();
}

bool Player::active() const {
    return params_.loop || t_ < clip_.duration;
}

float Player::duration() const {
    return params_.speed > 0.0f ? clip_.duration / params_.speed : clip_.duration;
}

void Player::sample() {
    // In the loop gap (t_ > duration) every clip has faded out; sampling
    // clamped at duration holds that blank state.
    float ts = std::min(t_, clip_.duration);
    for (size_t i = 0; i < clip_.tracks.size(); ++i)
        states_[i] = sampleTrack(clip_.tracks[i].keys, ts);
}

void Player::fireTags(float from, float to) {
    if (!onTag || to < from) return;
    for (const TagEvent& e : clip_.tags)
        if (e.t > from && e.t <= to) onTag(e.tag);
}

}  // namespace ge::hint
