// Copyright 2026 Marcelo Cantos
// SPDX-License-Identifier: Apache-2.0
//
// Engine-private — Obj-C protocol declarations that bridge `iap_apple.mm`
// (C++/Obj-C++) and `iap_apple.swift` (StoreKit 2 worker).
//
// The Swift class `GEStoreKit2BridgeImpl` conforms to `GEStoreKit2Bridge`
// so the C++ side can call it via a typed `id<GEStoreKit2Bridge>` without
// importing the autogenerated `<Target>-Swift.h`. Callbacks travel back
// in via `GEStoreKit2Listener`: the C++ side defines a concrete listener
// class (`GEStoreKit2ListenerImpl` in `iap_apple.mm`) and registers it on
// the bridge before any other call.
//
// Methods are intentionally *coarse* — one method per operation, no
// async returns. Swift fires callbacks asynchronously via the listener
// when the operation completes. This keeps the bridge minimal and the
// Swift side free to use `async/await` internally.

#pragma once

#if defined(__APPLE__)
#include <TargetConditionals.h>
#endif

#if defined(__APPLE__) && (TARGET_OS_IPHONE || TARGET_OS_TV || TARGET_OS_WATCH)

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

// Receiver of StoreKit 2 events. The C++ side implements this; the
// Swift bridge invokes it on the main thread when async work resolves.
@protocol GEStoreKit2Listener <NSObject>
- (void)onProductFetched:(NSString*)sku
                   title:(NSString*)title
             description:(NSString*)description
                   price:(NSString*)price
                currency:(NSString*)currency;
- (void)onTransactionUpdate:(NSString*)sku
                         ok:(BOOL)ok
                      error:(NSString*)error;
// Reports one entitlement at a time during the initial walk, then
// invokes onCurrentEntitlementsFinished once the walk completes.
- (void)onCurrentEntitlement:(NSString*)sku;
- (void)onCurrentEntitlementsFinished;
- (void)onRestoreFinished:(BOOL)ok error:(NSString*)error;
@end

// Public Swift class surfaced to Obj-C++. The implementation
// (GEStoreKit2BridgeImpl) lives in iap_apple.swift.
@protocol GEStoreKit2Bridge <NSObject>
@property (nonatomic, weak, nullable) id<GEStoreKit2Listener> listener;
- (void)start;
- (void)stop;
- (void)fetchProducts:(NSArray<NSString*>*)skus;
- (void)purchase:(NSString*)sku;
- (void)loadCurrentEntitlements;
- (void)restore;
@end

NS_ASSUME_NONNULL_END

#endif // __APPLE__ && (TARGET_OS_IPHONE || ...)
