// Copyright 2026 Marcelo Cantos
// SPDX-License-Identifier: Apache-2.0
//
// Apple StoreKit 2 backend for ge::iap (🎯T68 — replaces the earlier
// StoreKit 1 / SKPaymentQueue path from 🎯T65.2).
//
// Architecture:
//   * `iap_apple.swift` — `GEStoreKit2BridgeImpl` does the SK2 work
//     (Transaction.updates listener, Transaction.currentEntitlements
//     walk, Product.purchase, AppStore.sync). Pure Swift, async/await.
//     On-device JWS verification: only `.verified` transactions credit
//     entitlements; `.unverified` are logged and dropped.
//   * `iap_apple_bridge.h` — Obj-C protocols (`GEStoreKit2Bridge` +
//     `GEStoreKit2Listener`) so this file can talk to the Swift class
//     via typed `id<GEStoreKit2Bridge>` without importing the
//     autogenerated `<Target>-Swift.h`.
//   * `AppleStore` (this file) — implements `detail::Store`,
//     translates ge::iap's coarse API to Swift bridge calls, and
//     receives async callbacks through `GEStoreKit2ListenerImpl`.
//
// Bundle-ID prefixing (forward + reverse maps populated in setCatalogue)
// works the same as the SK1 path — Product::sku takes precedence when
// set, otherwise auto-prefix. Same T67 mechanic.
//
// macOS desktop: this file compiles to a single nullptr-returning
// `makePlatformStore()` so Module.mk builds (which include iap_apple.mm
// but don't compile the Swift bridge) link cleanly. The dispatcher in
// `iap.cpp` already defaults to stub on macOS, so the nullptr stub is
// the right behaviour — apps wanting Mac IAP would extend this path.

#include "iap_internal.h"

#if defined(__APPLE__)
#include <TargetConditionals.h>
#endif

#if defined(__APPLE__) && (TARGET_OS_IPHONE || TARGET_OS_TV || TARGET_OS_WATCH)

#import <Foundation/Foundation.h>
#import <Security/Security.h>

#import "iap_apple_bridge.h"

#include <spdlog/spdlog.h>

#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace ge::iap::detail {

namespace {

// Default auto-prefix: `<bundle-id>.<local-id>`. Used when Product::sku
// is unset or its `apple` field is empty (T67 mixed-mode).
std::string autoPrefixSku(const std::string& localId) {
    NSString* bundleId = [[NSBundle mainBundle] bundleIdentifier];
    if (!bundleId) return localId;
    return std::string([bundleId UTF8String]) + "." + localId;
}

std::string platformSkuFor(const Product& p) {
    if (p.sku && !p.sku->apple.empty()) return p.sku->apple;
    return autoPrefixSku(p.id);
}

std::string nsstr(NSString* _Nullable s) {
    return s ? std::string([s UTF8String]) : std::string{};
}

// ── Keychain entitlement cache (🎯T65.5) ─────────────────────────────
//
// StoreKit 2's currentEntitlements walk is async and takes ~1 s after
// process launch. Until it completes, owned() returns false even for
// entitled products — long enough for a paywall-gated screen to render
// the wrong state. The Keychain cache fills that gap: every confirmed
// entitlement is mirrored to Keychain (read instantly on next launch),
// and the StoreKit walk reconciles when it finishes (correcting
// revocations, refunds, family-sharing changes).
//
// Storage: one Keychain generic-password item per process bundle,
// payload is the newline-separated set of currently-owned local IDs.
// Accessibility: kSecAttrAccessibleAfterFirstUnlock — survives reboot
// once the user has unlocked once; not synced to iCloud Keychain
// (entitlements are per-device).

NSString* keychainService() {
    NSString* bundleId = [[NSBundle mainBundle] bundleIdentifier];
    return [NSString stringWithFormat:@"%@.ge.iap.entitlements",
            bundleId ?: @"unknown"];
}

NSMutableDictionary* keychainBaseQuery() {
    NSMutableDictionary* q = [NSMutableDictionary dictionary];
    q[(__bridge id)kSecClass]       = (__bridge id)kSecClassGenericPassword;
    q[(__bridge id)kSecAttrService] = keychainService();
    q[(__bridge id)kSecAttrAccount] = @"entitlements";
    return q;
}

std::unordered_set<std::string> loadKeychainEntitlements() {
    NSMutableDictionary* q = keychainBaseQuery();
    q[(__bridge id)kSecReturnData] = @YES;
    q[(__bridge id)kSecMatchLimit] = (__bridge id)kSecMatchLimitOne;

    CFTypeRef result = nullptr;
    OSStatus status = SecItemCopyMatching((__bridge CFDictionaryRef)q, &result);
    if (status == errSecItemNotFound) return {};
    if (status != errSecSuccess) {
        SPDLOG_WARN("AppleStore Keychain read failed: OSStatus {}", (int)status);
        return {};
    }
    NSData* data = (__bridge_transfer NSData*)result;
    NSString* blob = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
    if (!blob) return {};

    std::unordered_set<std::string> out;
    NSArray<NSString*>* lines = [blob componentsSeparatedByString:@"\n"];
    for (NSString* line in lines) {
        if (line.length == 0) continue;
        out.insert(std::string([line UTF8String]));
    }
    return out;
}

void saveKeychainEntitlements(const std::unordered_set<std::string>& entitled) {
    NSMutableString* joined = [NSMutableString string];
    bool first = true;
    for (const auto& id : entitled) {
        if (!first) [joined appendString:@"\n"];
        [joined appendString:[NSString stringWithUTF8String:id.c_str()]];
        first = false;
    }
    NSData* payload = [joined dataUsingEncoding:NSUTF8StringEncoding];

    NSMutableDictionary* q = keychainBaseQuery();
    OSStatus existing = SecItemCopyMatching((__bridge CFDictionaryRef)q, nullptr);
    if (existing == errSecSuccess) {
        NSDictionary* update = @{(__bridge id)kSecValueData: payload};
        OSStatus s = SecItemUpdate((__bridge CFDictionaryRef)q,
                                   (__bridge CFDictionaryRef)update);
        if (s != errSecSuccess) {
            SPDLOG_WARN("AppleStore Keychain update failed: OSStatus {}", (int)s);
        }
    } else {
        q[(__bridge id)kSecValueData]      = payload;
        q[(__bridge id)kSecAttrAccessible] = (__bridge id)kSecAttrAccessibleAfterFirstUnlock;
        OSStatus s = SecItemAdd((__bridge CFDictionaryRef)q, nullptr);
        if (s != errSecSuccess) {
            SPDLOG_WARN("AppleStore Keychain add failed: OSStatus {}", (int)s);
        }
    }
}

} // namespace

struct AppleStore : Store {
    mutable std::mutex                                  mu;
    std::unordered_map<std::string, Product>            catalogue;          // local id -> spec
    std::unordered_set<std::string>                     entitled;           // local ids
    std::unordered_map<std::string, LocalisedProduct>   localised;          // local id -> price/title
    std::unordered_map<std::string, BuyCallback>        pendingBuys;        // local id -> cb
    std::unordered_map<std::string, std::string>        platformSkuByLocal; // T67
    std::unordered_map<std::string, std::string>        localBySkuPlatform; // T67
    RestoreCallback                                     pendingRestore;
    id<GEStoreKit2Bridge> __strong                      bridge   = nil;
    NSObject<GEStoreKit2Listener>* __strong             listener = nil;

    AppleStore();
    ~AppleStore() override;

    void setCatalogue(std::vector<Product> next) override;
    bool owned(const std::string& id) const override;
    std::vector<LocalisedProduct> products() const override;
    void buy(const std::string& id, BuyCallback) override;
    void restore(RestoreCallback) override;

    void testingSetOwned(const std::string&, bool) override {
        SPDLOG_WARN("ge::iap::testing::setOwned has no effect against AppleStore — entitlements are owned by StoreKit");
    }
    void testingClearAll() override {
        SPDLOG_WARN("ge::iap::testing::clearAll has no effect against AppleStore — entitlements are owned by StoreKit");
    }

    // Listener callbacks (invoked from Swift on the main thread).
    void onProductFetched(const std::string& sku,
                          const std::string& title,
                          const std::string& description,
                          const std::string& price,
                          const std::string& currency);
    void onTransactionUpdate(const std::string& sku, bool ok, const std::string& error);
    void onCurrentEntitlement(const std::string& sku);
    void onCurrentEntitlementsFinished();
    void onRestoreFinished(bool ok, const std::string& error);
};

} // namespace ge::iap::detail

// ── Obj-C listener — receives Swift callbacks, forwards to AppleStore ──

@interface GEStoreKit2ListenerImpl : NSObject <GEStoreKit2Listener>
@property (assign, nonatomic) ge::iap::detail::AppleStore* owner;
@end

@implementation GEStoreKit2ListenerImpl
- (void)onProductFetched:(NSString*)sku
                   title:(NSString*)title
             description:(NSString*)description
                   price:(NSString*)price
                currency:(NSString*)currency {
    if (!self.owner) return;
    self.owner->onProductFetched(
        ge::iap::detail::nsstr(sku),
        ge::iap::detail::nsstr(title),
        ge::iap::detail::nsstr(description),
        ge::iap::detail::nsstr(price),
        ge::iap::detail::nsstr(currency));
}

- (void)onTransactionUpdate:(NSString*)sku ok:(BOOL)ok error:(NSString*)error {
    if (!self.owner) return;
    self.owner->onTransactionUpdate(
        ge::iap::detail::nsstr(sku),
        ok == YES,
        ge::iap::detail::nsstr(error));
}

- (void)onCurrentEntitlement:(NSString*)sku {
    if (!self.owner) return;
    self.owner->onCurrentEntitlement(ge::iap::detail::nsstr(sku));
}

- (void)onCurrentEntitlementsFinished {
    if (!self.owner) return;
    self.owner->onCurrentEntitlementsFinished();
}

- (void)onRestoreFinished:(BOOL)ok error:(NSString*)error {
    if (!self.owner) return;
    self.owner->onRestoreFinished(ok == YES, ge::iap::detail::nsstr(error));
}
@end

// ── AppleStore method bodies ────────────────────────────────────────

namespace ge::iap::detail {

AppleStore::AppleStore() {
    // 🎯T65.5: prime the entitlement set from Keychain so owned() returns
    // the right answer on frame 0. The async StoreKit walk
    // (loadCurrentEntitlements below) reconciles when it completes —
    // additions land in the set, and the post-walk save will drop any
    // IDs that StoreKit no longer credits (revoked, refunded, etc.).
    entitled = loadKeychainEntitlements();
    if (!entitled.empty()) {
        SPDLOG_INFO("AppleStore: primed {} entitlements from Keychain cache", entitled.size());
    }

    // 🎯T65.4: GE_IAP_MODE=local uses SKTestSession via
    // GEStoreKit2LocalBridgeImpl; platform (the default) uses the
    // production GEStoreKit2BridgeImpl.
    const char* envMode = std::getenv("GE_IAP_MODE");
    const bool localMode = envMode && std::string(envMode) == "local";
    NSString* className = localMode
        ? @"GEStoreKit2LocalBridgeImpl"
        : @"GEStoreKit2BridgeImpl";

    Class implClass = NSClassFromString(className);
    if (!implClass && localMode) {
        // Local bridge not compiled in — fall back to production bridge.
        SPDLOG_WARN("AppleStore: GEStoreKit2LocalBridgeImpl not found — iap_apple_local.swift missing from build; falling back to production bridge");
        implClass = NSClassFromString(@"GEStoreKit2BridgeImpl");
    }
    if (!implClass) {
        SPDLOG_ERROR("AppleStore: GEStoreKit2BridgeImpl not found — Swift bridge missing from build");
        return;
    }
    bridge = (id<GEStoreKit2Bridge>)[[implClass alloc] init];
    GEStoreKit2ListenerImpl* l = [[GEStoreKit2ListenerImpl alloc] init];
    l.owner = this;
    listener = l;
    bridge.listener = l;
    [bridge start];
    [bridge loadCurrentEntitlements];
}

AppleStore::~AppleStore() {
    [bridge stop];
    if (listener) {
        ((GEStoreKit2ListenerImpl*)listener).owner = nullptr;
        listener = nil;
    }
    if (bridge) {
        bridge.listener = nil;
        bridge = nil;
    }
}

void AppleStore::setCatalogue(std::vector<Product> next) {
    NSMutableArray<NSString*>* skus = [NSMutableArray array];
    {
        std::lock_guard lock(mu);
        for (const auto& p : next) {
            catalogue.try_emplace(p.id, p);
            std::string platformId = platformSkuFor(p);
            platformSkuByLocal[p.id]       = platformId;
            localBySkuPlatform[platformId] = p.id;
            [skus addObject:[NSString stringWithUTF8String:platformId.c_str()]];
        }
    }
    [bridge fetchProducts:skus];
}

bool AppleStore::owned(const std::string& id) const {
    std::lock_guard lock(mu);
    return entitled.contains(id);
}

std::vector<LocalisedProduct> AppleStore::products() const {
    std::lock_guard lock(mu);
    std::vector<LocalisedProduct> out;
    out.reserve(localised.size());
    for (const auto& [id, lp] : localised) out.push_back(lp);
    return out;
}

void AppleStore::buy(const std::string& id, BuyCallback cb) {
    std::string platformId;
    {
        std::lock_guard lock(mu);
        auto it = platformSkuByLocal.find(id);
        if (it == platformSkuByLocal.end()) {
            Result r{.ok = false, .id = id, .error = "unknown product"};
            if (cb) cb(std::move(r));
            return;
        }
        platformId = it->second;
        pendingBuys[id] = std::move(cb);
    }
    [bridge purchase:[NSString stringWithUTF8String:platformId.c_str()]];
}

void AppleStore::restore(RestoreCallback cb) {
    {
        std::lock_guard lock(mu);
        pendingRestore = std::move(cb);
    }
    [bridge restore];
}

// ── Listener callbacks (called from Swift on the main thread) ──

void AppleStore::onProductFetched(const std::string& sku,
                                  const std::string& title,
                                  const std::string& description,
                                  const std::string& price,
                                  const std::string& currency) {
    std::lock_guard lock(mu);
    auto it = localBySkuPlatform.find(sku);
    if (it == localBySkuPlatform.end()) {
        SPDLOG_WARN("StoreKit 2 returned unmapped product identifier: {}", sku);
        return;
    }
    localised[it->second] = {
        .id          = it->second,
        .title       = title,
        .description = description,
        .price       = price,
        .currency    = currency,
    };
}

void AppleStore::onTransactionUpdate(const std::string& sku, bool ok, const std::string& error) {
    std::string localId;
    bool isConsumable = false;
    bool persist = false;
    std::unordered_set<std::string> snapshot;
    BuyCallback cb;
    {
        std::lock_guard lock(mu);
        auto skuIt = localBySkuPlatform.find(sku);
        if (skuIt == localBySkuPlatform.end()) {
            SPDLOG_WARN("Transaction update for unmapped product identifier: {}", sku);
            return;
        }
        localId = skuIt->second;
        auto pIt = catalogue.find(localId);
        if (pIt != catalogue.end()) isConsumable = pIt->second.type == Type::Consumable;
        if (ok && !isConsumable) {
            auto [_, inserted] = entitled.insert(localId);
            if (inserted) {
                persist = true;
                snapshot = entitled;  // copy under lock for off-lock write
            }
        }
        auto cbIt = pendingBuys.find(localId);
        if (cbIt != pendingBuys.end()) {
            cb = std::move(cbIt->second);
            pendingBuys.erase(cbIt);
        }
    }
    if (persist) saveKeychainEntitlements(snapshot);
    if (cb) cb({.ok = ok, .id = localId, .error = error});
}

void AppleStore::onCurrentEntitlement(const std::string& sku) {
    // Initial walk (silent auto-restore): credit non-consumables to the
    // cache. The reverse map may not yet contain this SKU if the
    // catalogue hasn't been registered — that's fine, the entitlement
    // just sits in StoreKit's records and we'll pick it up next launch
    // once the consumer calls setCatalogue.
    std::lock_guard lock(mu);
    auto it = localBySkuPlatform.find(sku);
    if (it == localBySkuPlatform.end()) {
        SPDLOG_INFO("StoreKit 2 currentEntitlements: unmapped {} — will pick up after setCatalogue", sku);
        return;
    }
    entitled.insert(it->second);
}

void AppleStore::onCurrentEntitlementsFinished() {
    // Phase marker — the entitlement cache is now populated for SKUs
    // we know about. 🎯T65.5: persist the reconciled set so the next
    // launch primes from Keychain with whatever StoreKit confirms now
    // (including any subset/superset changes vs. the Keychain prime).
    std::unordered_set<std::string> snapshot;
    {
        std::lock_guard lock(mu);
        snapshot = entitled;
    }
    saveKeychainEntitlements(snapshot);
    SPDLOG_INFO("AppleStore: currentEntitlements walk complete ({} entitled)", snapshot.size());
}

void AppleStore::onRestoreFinished(bool ok, const std::string& error) {
    RestoreCallback cb;
    std::unordered_set<std::string> snapshot;
    bool persist = false;
    {
        std::lock_guard lock(mu);
        cb = std::move(pendingRestore);
        pendingRestore = {};
        if (ok) {
            persist = true;
            snapshot = entitled;
        }
    }
    if (persist) saveKeychainEntitlements(snapshot);
    if (cb) cb({.ok = ok, .id = {}, .error = error});
}

std::unique_ptr<Store> makePlatformStore() {
    return std::make_unique<AppleStore>();
}

} // namespace ge::iap::detail

#elif defined(__APPLE__)

// macOS desktop fallback: no platform store. Module.mk's macOS build
// includes this file but doesn't compile the Swift bridge, so the
// iOS path can't link here. Dispatcher in iap.cpp defaults to stub
// on macOS so the nullptr return is exactly what's expected — apps
// that genuinely want Mac App Store IAP would extend this path with
// a separate SK2 binding.

#include <memory>

namespace ge::iap::detail {
std::unique_ptr<Store> makePlatformStore() { return nullptr; }
} // namespace ge::iap::detail

#endif // __APPLE__ && (TARGET_OS_IPHONE || ...)
