#!/usr/bin/env python3
# Copyright 2026 Marcelo Cantos
# SPDX-License-Identifier: Apache-2.0
#
# Generate the sokol_gfx dispatch layer (🎯T107) — the mechanism that lets ge's
# pervasive sg_* calls reach a sokol backend that lives in a *separate* .so with
# all sg_* hidden. The backend .so (libgesokol-vk / -gles) is compiled with
# SOKOL_IMPL + its backend; it exports exactly ONE visibility("default") symbol
# (ge_sokol_bind_<backend>) that installs a table of all 159 sg_* function
# pointers. libge links the generated *forwarder shim* (real sg_* symbols that
# call through the installed table), so every existing call site is unchanged.
#
# Emits three files into tools/sokol-dispatch/generated/:
#   ge_sokol_dispatch.h   — struct ge_sg_api { fn ptrs }; + g_ge_sg_api + bind decl
#   ge_sokol_dispatch.c   — the forwarders (sg_X -> g_ge_sg_api->sg_X). -> libge
#   ge_sokol_fill.inc     — ge_sg_api_fill() body (a->sg_X = sg_X). -> backend .so
#
# Re-run after a sokol bump:  tools/sokol-dispatch/gen.py
#
# The parser handles sokol_gfx.h's regular declaration style:
#   SOKOL_GFX_API_DECL <ret> sg_<name>(<params>);
# Params are `type name`, `type name[]`, or `void`. Anything it can't parse is
# reported and aborts (so a sokol API shape change is loud, not silently dropped).

import re
import sys
from pathlib import Path

GE = Path(__file__).resolve().parents[2]
HDR = GE / "vendor/github.com/floooh/sokol/sokol_gfx.h"
OUT = Path(__file__).resolve().parent / "generated"

# Public API only (before the SOKOL_GFX_IMPL block).
text = HDR.read_text()
impl = text.find("#ifdef SOKOL_GFX_IMPL")
assert impl > 0, "could not find SOKOL_GFX_IMPL boundary"
public = text[:impl]

# Grab each real `SOKOL_GFX_API_DECL <ret> sg_name(<params>);`. Require an
# sg_*( and forbid # / ; / braces in the body so the macro-definition lines
# (`#define SOKOL_GFX_API_DECL ...`) and statement spans can't match.
decls = re.findall(r"SOKOL_GFX_API_DECL\s+([^;{}#]*?\bsg_\w+\s*\([^;{}#]*?\))\s*;",
                   public, re.DOTALL)

FnT = []  # (ret, name, params_src, arg_names)


def split_top_level(s):
    """Split a parameter list on top-level commas (no nested parens here)."""
    out, depth, cur = [], 0, ""
    for ch in s:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur)
    return out


def parse_param_name(p):
    p = p.strip()
    if p == "void" or p == "":
        return None
    # last identifier token is the parameter name (strip trailing [] if present)
    p = re.sub(r"\[\s*\]\s*$", "", p).strip()
    m = re.search(r"([A-Za-z_]\w*)\s*$", p)
    if not m:
        raise ValueError(f"cannot parse param name in: {p!r}")
    return m.group(1)


for d in decls:
    d = " ".join(d.split())  # collapse whitespace
    m = re.match(r"^(.*?\**)\s*\b([A-Za-z_]\w*)\s*\((.*)\)$", d)
    if not m:
        print(f"SKIP (unparsed decl): {d}", file=sys.stderr)
        sys.exit(2)
    ret, name, params = m.group(1).strip(), m.group(2), m.group(3).strip()
    if not name.startswith("sg_"):
        continue  # ignore non-sg_ decls if any slip in
    if params == "" or params == "void":
        arg_names, params_src = [], "void"
    else:
        parts = split_top_level(params)
        arg_names = [parse_param_name(p) for p in parts]
        params_src = ", ".join(p.strip() for p in parts)
    FnT.append((ret, name, params_src, arg_names))

if not FnT:
    print("error: no sg_* declarations parsed", file=sys.stderr)
    sys.exit(2)

OUT.mkdir(parents=True, exist_ok=True)
hdr, fwd, fill = [], [], []

GUARD = "GE_SOKOL_DISPATCH_H_"
hdr.append("// GENERATED by tools/sokol-dispatch/gen.py — do not edit. (🎯T107)")
hdr.append(f"#ifndef {GUARD}\n#define {GUARD}")
hdr.append('#include "sokol_gfx.h"')
hdr.append("#ifdef __cplusplus\nextern \"C\" {\n#endif")
hdr.append("\n// Table of every public sokol_gfx entry point. Filled by a backend")
hdr.append("// .so's ge_sokol_bind_<backend>() and consulted by the forwarder shim.")
hdr.append("typedef struct ge_sg_api {")
for ret, name, params_src, _ in FnT:
    hdr.append(f"    {ret} (*{name})({params_src});")
hdr.append("} ge_sg_api;")
hdr.append("\n// The installed table (NULL until a backend binds). Defined in the shim.")
hdr.append("extern const ge_sg_api* g_ge_sg_api;")
hdr.append("// Backend .so entrypoints install the table; named per backend so the")
hdr.append("// loader picks one and co-mapping can never collide.")
hdr.append("void ge_sokol_set_api(const ge_sg_api* api);")
hdr.append("#ifdef __cplusplus\n}\n#endif")
hdr.append(f"#endif  // {GUARD}")

fwd.append("// GENERATED by tools/sokol-dispatch/gen.py — do not edit. (🎯T107)")
fwd.append("// Forwarder shim: real sg_* symbols that dispatch through the installed")
fwd.append("// backend table. Linked into libge so ge's call sites are unchanged.")
fwd.append('#include "ge_sokol_dispatch.h"')
fwd.append("const ge_sg_api* g_ge_sg_api = 0;")
fwd.append("void ge_sokol_set_api(const ge_sg_api* api) { g_ge_sg_api = api; }")
for ret, name, params_src, arg_names in FnT:
    call = f"g_ge_sg_api->{name}({', '.join(arg_names)})"
    ret_kw = "" if ret.replace(" ", "") == "void" else "return "
    sig = f"{ret} {name}({params_src})"
    fwd.append(f"{sig} {{ {ret_kw}{call}; }}")

fill.append("// GENERATED by tools/sokol-dispatch/gen.py — do not edit. (🎯T107)")
fill.append("// #include this inside a backend .so's ge_sokol_bind_<backend>() to")
fill.append("// publish its (hidden) sokol impl through the dispatch table.")
fill.append("// Expects a `ge_sg_api* _a` in scope.")
for _, name, _, _ in FnT:
    fill.append(f"_a->{name} = {name};")

(OUT / "ge_sokol_dispatch.h").write_text("\n".join(hdr) + "\n")
(OUT / "ge_sokol_dispatch.c").write_text("\n".join(fwd) + "\n")
(OUT / "ge_sokol_fill.inc").write_text("\n".join(fill) + "\n")
print(f"generated dispatch for {len(FnT)} sg_* entry points -> {OUT}")
